export const ATOM_ID_SYMBOL = Symbol('ATOM_ID_SYMBOL');
export const ATOM_ID_STRINGIFIED_SYMBOL = Symbol('ATOM_ID_STRINGIFIED_SYMBOL');
export const ATOM_EXECUTOR_SYMBOL = Symbol('ATOM_EXECUTOR_SYMBOL');
export const ATOM_INITIAL_VALUE_SYMBOL = Symbol('ATOM_INITIAL_VALUE_SYMBOL');
